version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: security
    volumes:
      - ./src/main/resources:/var/lib/postgres/data
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
