spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
#    url: jdbc:postgresql://localhost:5432/tasks_hw5
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
#spring:
#  datasource:
#    url: jdbc:h2:file:./mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties.hibernate:
#      show_sql: true
#      format_sql: true
#      ddl-auto: update
#  sql:
#    init:
#      mode: always
app:
  image:
    path: "./images"